
import { TrailListItem, Race } from './types';

// Fallback trails — a small set used when Supabase is unavailable
export const INITIAL_TRAILS: TrailListItem[] = [
  {
    id: 'wta_mount-si',
    name: 'Mount Si',
    difficulty: 9.87,
    calculatedDifficulty: 'Hard',
    rating: 4.0,
    numVotes: 284,
    distance: 8.0,
    elevation: 3150,
    highestPoint: 3900,
    trailheadLat: 47.4879799075,
    trailheadLng: -121.723121166,
    surface: 'Scree / Talus',
    routeType: 'roundtrip',
    waterSource: 'Natural Lake',
    imageUrl: 'https://www.wta.org/site_images/hikes/15148635572_d7cb258404_o.jpg/@@download/image/Mount Si. Photo by VOXroy.jpeg',
    difficultyScore010: 6.7,
  },
  {
    id: 'wta_rattlesnake-ledge',
    name: 'Rattlesnake Ledge',
    difficulty: 4.36,
    calculatedDifficulty: 'Moderate',
    rating: 4.1,
    numVotes: 426,
    distance: 4.0,
    elevation: 1160,
    highestPoint: 2078,
    trailheadLat: 47.4347127863,
    trailheadLng: -121.768745691,
    surface: 'Rocky / Technical',
    routeType: 'roundtrip',
    waterSource: 'Natural Lake',
    imageUrl: 'https://www.wta.org/site_images/hikes/rattlesnake-ledge-by-mmumford11.jpeg/@@download/image/rattlesnake ledge by mmumford11.jpeg',
    difficultyScore010: 4.2,
  },
  {
    id: 'wta_snow-lake',
    name: 'Snow Lake',
    difficulty: 7.45,
    calculatedDifficulty: 'Moderate/Hard',
    rating: 4.2,
    numVotes: 226,
    distance: 7.2,
    elevation: 1800,
    highestPoint: 4400,
    trailheadLat: 47.4454166667,
    trailheadLng: -121.423016667,
    surface: 'Scree / Talus',
    routeType: 'roundtrip',
    waterSource: 'Natural Lake',
    imageUrl: 'https://www.wta.org/site_images/hikes/dsc_0030.jpg/@@download/image/Snow Lake by JaidennC.jpg',
    difficultyScore010: 6.4,
  },
];

export const INITIAL_RACES: Race[] = [
  {
    id: 'r1',
    name: 'UTMB® Mont-Blanc',
    location: 'Chamonix, FR',
    country: 'France',
    date: 'Aug 24, 2026 • Monday',
    type: 'UTMB 100M',
    distance: '171KM',
    distanceKm: 171,
    elevation: '10,000M+',
    rating: 5.0,
    difficultyRank: 5,
    reviewCount: '15.4k Reviews',
    imageUrl: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&q=80&w=800&h=400',
    qualifiers: ['UTMB Index / Stones']
  },
  {
    id: 'r2',
    name: 'Western States Endurance Run',
    location: 'California, US',
    country: 'USA',
    date: 'June 27, 2026 • Saturday',
    type: 'WSER 100M',
    distance: '161KM',
    distanceKm: 161,
    elevation: '5,500M+',
    rating: 5.0,
    difficultyRank: 5,
    reviewCount: '12k Reviews',
    imageUrl: 'https://images.unsplash.com/photo-1596524430615-b46475ddff6e?auto=format&fit=crop&q=80&w=800&h=400',
    qualifiers: ['Western States (WSER)']
  },
  {
    id: 'r3',
    name: 'Tarawera Ultramarathon',
    location: 'Rotorua, NZ',
    country: 'New Zealand',
    date: 'Feb 14, 2026 • Saturday',
    type: 'Miler',
    distance: '165KM',
    distanceKm: 165,
    elevation: '4,500M+',
    rating: 4.8,
    difficultyRank: 4,
    reviewCount: '3.2k Reviews',
    imageUrl: 'https://images.unsplash.com/photo-1524230507669-5ff9e996bb5e?auto=format&fit=crop&q=80&w=800&h=400',
    qualifiers: ['Western States (WSER)', 'UTMB Index / Stones']
  },
  {
    id: 'r4',
    name: 'Black Canyon Ultras',
    location: 'Arizona, US',
    country: 'USA',
    date: 'Feb 7, 2026 • Saturday',
    type: 'Golden Ticket',
    distance: '100KM',
    distanceKm: 100,
    elevation: '1,500M+',
    rating: 4.7,
    difficultyRank: 3,
    reviewCount: '2.1k Reviews',
    imageUrl: 'https://images.unsplash.com/photo-1469317532191-6359be485351?auto=format&fit=crop&q=80&w=800&h=400',
    qualifiers: ['Western States (WSER)']
  },
  {
    id: 'r5',
    name: 'HURT 100',
    location: 'Honolulu, HI',
    country: 'USA',
    date: 'Jan 17, 2026 • Saturday',
    type: 'Hardrock Qualifier',
    distance: '161KM',
    distanceKm: 161,
    elevation: '7,500M+',
    rating: 4.9,
    difficultyRank: 5,
    reviewCount: '800 Reviews',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=800&h=400',
    qualifiers: ['Hardrock 100', 'UTMB Index / Stones']
  },
  {
    id: 'r6',
    name: 'Zegama-Aizkorri',
    location: 'Zegama, ES',
    country: 'Spain',
    date: 'May 17, 2026 • Sunday',
    type: 'Skyrunning',
    distance: '42KM',
    distanceKm: 42,
    elevation: '2,700M+',
    rating: 5.0,
    difficultyRank: 4,
    reviewCount: '10k Reviews',
    imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80&w=800&h=400',
    qualifiers: ['UTMB Index / Stones']
  },
  {
    id: 'r7',
    name: 'Hardrock 100',
    location: 'Silverton, CO',
    country: 'USA',
    date: 'July 10, 2026 • Friday',
    type: 'San Juan Classic',
    distance: '161KM',
    distanceKm: 161,
    elevation: '10,000M+',
    rating: 5.0,
    difficultyRank: 5,
    reviewCount: '1.5k Reviews',
    imageUrl: 'https://images.unsplash.com/photo-1464457312035-3d7d0e0c058e?auto=format&fit=crop&q=80&w=800&h=400',
    qualifiers: ['Western States (WSER)', 'UTMB Index / Stones']
  },
  {
    id: 'r8',
    name: 'Lavaredo Ultra Trail',
    location: 'Cortina, IT',
    country: 'Italy',
    date: 'June 25, 2026 • Thursday',
    type: 'Dolomites Major',
    distance: '120KM',
    distanceKm: 120,
    elevation: '5,800M+',
    rating: 4.9,
    difficultyRank: 4,
    reviewCount: '4k Reviews',
    imageUrl: 'https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&q=80&w=800&h=400',
    qualifiers: ['UTMB Index / Stones', 'Western States (WSER)']
  }
];

export const SURFACE_OPTIONS = [
  'Dirt/Soil', 'Gravel', 'Rocky / Technical', 'Rooty', 'Sand', 'Mud',
  'Snow / Ice', 'Pavement', 'Scree / Talus', 'Boardwalk / Wood'
];
